### ISSUE TITLE
README doesn't show correctly on https://crates.io/crates/accesskit

### ISSUE THREAD

**Issue by yerke** [AccessKit/accesskit#129]
Right now it just shows:
```
../README.md
```

**Comment by DataTriny** [comment]
Hi, this is strange! This issue seems to have been introduced with `accesskit` version `0.4.0`, [previous version displays fine](https://crates.io/crates/accesskit/0.3.0). Yet [c318360](https://github.com/AccessKit/accesskit/commit/c3183604bd8398976ceb991a24e469e5939a1e34) didn't change anything related to this, I think.

Also affects [libs.rs](https://lib.rs/crates/accesskit).
