### ISSUE TITLE
zbus panic on Linux

### ISSUE THREAD

**Issue by lunixbochs** [AccessKit/accesskit#227]
I get this panic when opening a winit window that creates an AccessKit adapter on Linux.
This is executing in the winit main thread. I called `accesskit_winit::Adapter::with_action_handler` from my own code.

```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-3.7.0/src/abstractions/executor.rs:62:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: tokio::runtime::scheduler::Handle::current
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/mod.rs:57:27
   4: tokio::runtime::handle::Handle::current
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/handle.rs:102:20
   5: tokio::task::spawn::spawn_inner
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/task/spawn.rs:184:22
   6: tokio::task::spawn::spawn
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/task/spawn.rs:171:13
   7: zbus::abstractions::executor::Executor::spawn
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-3.7.0/src/abstractions/executor.rs:62:27
   8: accesskit_unix::adapter::Adapter::new
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_unix-0.3.2/src/adapter.rs:45:26
   9: accesskit_winit::platform_impl::platform::Adapter::new
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_winit-0.12.3/src/platform_impl/unix.rs:21:23
  10: accesskit_winit::Adapter::with_action_handler
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_winit-0.12.3/src/lib.rs:170:23
```

**Comment by mwcampbell** [comment]
Please provide the output of `cargo tree`. Make sure to either attach it, or enclose it in a Markdown code block to preserve formatting. I'm asking for this because AccessKit doesn't use zbus's tokio feature; it uses the async-io feature instead. But I wonder if you have zbus with the tokio feature somewhere else in your transitive dependencies.

**Comment by lunixbochs** [comment]
It's not transitive - I use zbus with the tokio feature in my project.

**Comment by mwcampbell** [comment]
Then I suppose accesskit_unix needs to have async-io and tokio features, and work with both runtimes. @DataTriny Can you look into this?

@lunixbochs Just curious, what project are you using this in? If you can't share, no worries.

**Comment by lunixbochs** [comment]
> Then I suppose accesskit_unix needs to have async-io and tokio features, and work with both runtimes. @DataTriny Can you look into this?

zbus still feels really fragile here, I'm now worried something else in my dep tree will have the same problem. zbus can only work if everything in your dependency tree uses the same executor, this is clearly a bug in the zbus api/design :(

> Just curious, what project are you using this in?

I'm porting the core app/ui in [Talon](https://talonvoice.com) from Qt to Rust (egui) + a cool actor model system I built for UI + a handful of custom crates for stuff like better tray icon/menu and clipboard support to bring things up to par with my Qt codebase. I'm hoping to not regress on screen reader support in the process, as Qt native windows come with accessibility integration for free.

FWIW here are my results so far trying latest accesskit with egui in Talon (I'm on latest winit and I patched egui to use latest accesskit):
- macOS: an AccessKit node shows up in accessibility inspector but doesn't have an accessibility tree under it.
- Windows: I'm building my app with mingw and I haven't figured out how to link to uiautomationcore.dll yet.
- Linux: encountered the above crash. I'll try to work around it now that I know about the executor issue.

**Comment by mwcampbell** [comment]
@lunixbochs I'd like to work with you to debug the macOS issue. Where would be a convenient place for us to chat about that, so we don't clutter this issue?

**Comment by lunixbochs** [comment]
The [Talon slack](https://talonvoice.com/chat)?

**Comment by mwcampbell** [comment]
@lunixbochs OK, I'm on the Talon Slack now. I don't know how to find you there, but you should be able to DM me, or mention me on an appropriate channel if you prefer.

**Comment by DataTriny** [comment]
Hi there,

I already suggested adding `async-io` and `tokio` features [here](https://github.com/AccessKit/accesskit/pull/198#issuecomment-1368122586).

But actually doing it is tricky. We rely on zbus `blocking::Connection`'s executor to dispatch our events in a non-blocking fashion, but for the rest we rely on zbus blocking wrappers. What this mean in a tokio environment is that the event dispatching task will fail if `Adapter::new` is not called inside an async context, but doing so will impact all the other calls because the blocking wrappers try to spin their own runtime, which is not allowed inside another runtime.

```
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-3.10.0/src/utils.rs:50:14
```

The easiest (and maybe cleanest) way to solve this I see right now would be to offer both a blocking and an async API. If we want to keep a purely blocking API, I don't see how we could detect wether the caller:
- has started an async runtime, and so we should await futures until completion,
- has not started an async runtime, so we should start our own or use zbus blocking API.

Providing both a blocking and an async API would require significant changes under the hood, but we don't have many public function so the scope is quite narrow.

**Comment by lunixbochs** [comment]
Winit is currently a blocking runtime, and the only way for me to really own a winit Window is on the winit main thread in the synchronous runloop. Even though I have tokio code, it's not on this thread.

**Comment by lunixbochs** [comment]
as a workaround, I think we should add a tokio feature that just runs zbus in a tokio single thread executor, so at least people enabling the zbus tokio feature can bypass the crash

I think the more complicated answer would be to make a public async api for accesskit so the user can manage this themselves, but I kind of doubt many people will want to do that.
