### ISSUE TITLE
Need methods for traversing nodes, including unignored nodes

### ISSUE THREAD

**Issue by mwcampbell** [AccessKit/accesskit#4]
Belatedly opening an issue for this. #3 is addressing this; I just need to review it.

**Comment by DataTriny** [comment]
Some custom iterators that are part of #3 currently yield `NodeId` when they should return `Node<'_>`,. This force us to perform more hash table lookups due to the fact that the `Iterator` trait is not able to yield items that reference the custom iterator struct itself. It appears that this is a well-known issue of current Rust, and that Generic Associated Types could improve the situation.
Therefore, I would suggest keeping this issue open, or opening a dedicated one so we can track this optimization opportunity.

**Comment by mwcampbell** [comment]
See #39 for a discussion on the lifetime challenges.
