### ISSUE TITLE
Consider using `windows-sys` instead of `windows`

### ISSUE THREAD

**Issue by SkiFire13** [AccessKit/accesskit#446]
The `windows` crate is a bottleneck in many larger programs. Part of the problem is that it is often duplicated due to dependencies requiring different incompatible versions, which is being tackled in #440. However by fixing this another problem comes up: in the remaining copy of `windows` crate a lot more features gets enabled together, and that makes its compile times baloon.

For example I have observed a `windows` crate used by both `cpal` and `accesskit_windows` taking ~50 seconds to compile, but only 25 seconds when disabling `accesskit_windows`, so it is clear to me that just sharing one version of `windows` between dependencies won't totally solve the problem.

Hence the request to consider using `windows-sys`. While the `windows` crate exposes some convenient APIs, that's also the reason it is very slow to compile. In comparison the `windows-sys` is a lot more low-level and barebones, consisting of mostly extern declarations, but in return it is much faster to compile. It is also a dependency of the `windows` crate, so it will have to be compiled anyway, meaning the time saved from not compiling the `windows` crate or not enabling some of its features will be pure gain.

**Comment by mwcampbell** [comment]
I appreciate the importance of keeping compile time in check. I hesitate to say no to this, because I want to make AccessKit acceptable to as many developers as possible. But I believe I have to say no to this one.

There are two problems with windows-sys:

1. It doesn't actually contain the definitions we need to either use or implement COM interfaces. So we'd have to write our own definitions by hand, or somehow extract just the bits we need from the windows crate, and either of these things is a time-consuming, error-prone process that distracts us from the mission of our project.
2. Even if windows-sys did include raw, low-level definitions for COM interfaces as it does for direct functions, e.g. by providing vtable structs, there's still a reason to use the windows crate: The more we rely on raw, unsafe FFI, the more we're negating one of the principal reasons to choose Rust in the first place. At that point, we might as well write AccessKit in C. Again, that would be a distraction from what we're trying to achieve with this project.

So, while I appreciate the concern about compile time, I'm firmly rejecting this suggested solution.
