### ISSUE TITLE
Basic Unix adapter

### ISSUE THREAD

**Issue by DataTriny** [AccessKit/accesskit#56]
Unlike Chromium, we decided not to rely on ATK (the GTK accessibility layer) for our Unix adapter. Reasons include:

- GTK 4 does not use ATK anymore, effectively deprecating it.
- We don't want to force users of AccessKit to depend on GTK if they don't already.
- GObject management is ugly in Rust, and event handling for ATK would also be.

Instead, we will directly implement the AT-SPI protocol ourselves, like the Qt framework did.

AT-SPI sits on top of D-BUS. To avoid repetitive D-Bus message handling, we will use the high-level [zbus](https://crates.io/crates/zbus) crate.

To avoid duplicating efforts, we will share as much code as possible with the [atspi](https://crates.io/crates/atspi) crate.

A very minimal Unix adapter should be capable of exposing a basic application (a window with two buttons for instance).

Here is the list of required features for this first version:

- Implement most of the `org.a11y.atspi.Application`: `GetApplicationBusAddress` will probably be skipped for now.
- Implement most methods and properties of `org.a11y.atspi.Accessible`: name, description, ID, role...
- Implement hit-testing through `org.a11y.atspi.Component'.
- Implement AT action requests support through `org.a11y.atspi.Action`.
- Implement basic numeric value widget support through `org.a11y.atspi.Value`.
- Include an example demonstrating a basic window (X11?).
- Update `accesskit_winit` to support the new adapter.

Current progress can be tracked [here](https://github.com/DataTriny/accesskit/tree/unix_basics).

**Comment by federicomenaquintero** [comment]
Hello, AccessKit people!  I'm one of the maintainers of at-spi2-core, and I wanted to thank you for working on AccessKit!

I'm in the process of cleaning up the accessibility stack (adding CI, removing obsolete code, adding tests, documenting things, etc.).  I'm glad that you are using the DBus interfaces directly instead of atk; this is the right call.  If you end up writing documentation for yourselves about atspi interfaces that are not documented yet (e.g. all the XML ifaces that I haven't gone through yet), please tell me so I can include your docs!  Or submit a MR at https://gitlab.gnome.org/GNOME/at-spi2-core/

Of course if you have questions about how atspi works, or how Orca actually uses it, don't hesitate to ask.  I'm in the process of learning the atspi->pyatspi2->orca part of the stack (I've been working on the registry side of things so far), but I'll be glad to help.

May I also invite you to the https://matrix.to/#/#a11y:gnome.org channel where we discuss atspi in general.

**Comment by DataTriny** [comment]
Hello @federicomenaquintero ,

Thank you so much for maintaining the AT-SPI project.

FYI we now rely on the [atspi](https://github.com/odilia-app/atspi) library and we'll try to share as much code as possible to avoid duplicating work. Good documentation is one of our goal. You can check it [here](https://docs.rs/atspi).

I hope to have this feature merged before the end of the year.
